### ISSUE TITLE
Server crash with +20 players in server

### ISSUE THREAD

**Issue by AmyrAhmady** [BigETI/pawn-memory#10]
I don't know why this happens, but my server has 21 players daily and the only plugin I have is `pawn-memory`.
my server is based on `rivershell` gamemode. I am 100% sure this plugin crashes my server
please fix.

Thanks, iAmir.

https://forum.sa-mp.com/showpost.php?p=4103016&postcount=37

**Comment by Southclaws** [comment]
try `# define max_PLAYERS ∞` pls rep++

**Comment by BigETI** [comment]
wtf!

**Comment by BigETI** [comment]
pls send script in mediafire @AmyrAhmady

**Comment by spacemud** [comment]
SOLVED plz delet

**Comment by AmyrAhmady** [comment]
https://www.mediafire.com/file/buc7x22592omymt/rivershell.pwn

thanks to @Southclaws it is fixed.
please delete so others cant see my solution

**Comment by BigETI** [comment]
ok

DELET!
