### ISSUE TITLE
Not able to compile on Linux

### ISSUE THREAD

**Issue by frostgaming** [BigETI/pawn-memory#3]
Hello!

I'm not able to compile this plugin on Linux because your source/makefile requires GCC 4.9.x

```
[root@eu pawn-memory]# make
gcc -std=c++14 -c -m32 -fPIC -O3 -w -DLINUX -I./SDK/amx/ ./SDK/amx/*.c
gcc: error: unrecognized command line option ‘-std=c++14’
make: *** [all] Error 1
```
All of the boxes I have use GCC 4.8 and CentOS 6/7 mainstream only has GCC 4.8.

```
[root@eu pawn-memory]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
```

I'm using the latest RHEL 7.x:
```
[root@eu pawn-memory]# cat /etc/*release* | grep -E 7.[0-9]+ | head -n 1
CentOS Linux release 7.4.1708 (Core)
```

I've already tried upgrading to GCC 4.9.x (which took ~45 minutes to compile GCC 4.9) on another server just to get it to compile, but ran into other issues:
```
[root@dal1 pawn-memory]# make
gcc -std=c++14 -c -m32 -fPIC -O3 -w -DLINUX -I./SDK/amx/ ./SDK/amx/*.c
g++ -std=c++14 -c -m32 -fPIC -O3 -w -DLINUX -I./SDK/amx/ ./SDK/*.cpp
g++ -std=c++14 -c -m32 -fPIC -O3 -w -DLINUX -I./SDK/amx/ ./*.cpp
g++ -m32 -O2 -fshort-wchar -shared -o "./memory.so" *.o
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/crtbeginS.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/crtendS.o' is incompatible with i386 output
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

The reason why I want to recompile this plugin is because the .so we have already is compiled against another libstdc++ version that we don't have:
``` 
[05:30:27]   Failed (/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by plugins/memory.so))
```

Any suggestions?

**Comment by BigETI** [comment]
You need to install ia32-libs. Your compiler doesn't support C++14. You can change the C++ version in makefile to C++11.

**Comment by frostgaming** [comment]
ia32-libs is not a package that exists in CentOS 6 or 7.
```
[root@eu src]# yum install ia32-libs
Loaded plugins: fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 91.197.228.252
 * cpanel-addons-production-feed: 91.197.228.252
 * base: mirrors.coreix.net
 * epel: mirrors.coreix.net
 * extras: mirror.sov.uk.goscomb.net
 * updates: mirrors.coreix.net
No package ia32-libs available.
```

I've already installed the compat packages (glibc.i686/libstdc++i686/i386/etc) and that didn't help.

Anyway, I changed the compiler version to c++11 and I was able to compile that way. Seems to be fine now.

You might want to consider changing your makefile to c++11 so that it allows RHEL users to compile the plugin. Or alternatively, create a "configure" file to detect the GCC version/environment and regenerate a makefile.

Thanks for the help.

**Comment by frostgaming** [comment]
I'll close this now as this is resolved. Atleast if others have the problem they can see this issue and use the workaround here. 

Great work on this plugin by the way!
