### ISSUE TITLE
Curyllic character encoding

### ISSUE THREAD

**Issue by pawnoholic** [BigETI/pawn-memory#9]
Hi, everybody!

I faced the problem of memory russian characters:

```
new string[24] = "Русский текст";

MEM_set_arr(ptr, 0, string, sizeof(string));
MEM_get_arr(ptr, 0, string, sizeof(string));

print(string); --> ������� �����
```

Can this be fixed in the next version?

**Comment by BigETI** [comment]
Neither `MEM_set_arr` nor `MEM_get_arr` will do anything with character encoding. The content should be as it is, only if enough space has been allocated. How do you allocate memory in the first place? Try printing that string before `MEM_set_arr` and `MEM_get_arr`.

**Comment by pawnoholic** [comment]
Forgive my stupidity.

Indeed, the problem turned out to be in the shell encoding.
